services:
  web:
    build:
      context: .
      args:
        API_URL: http://evcomp-api:8080/api
        NEXT_TELEMETRY_DISABLED: "1"
    container_name: evcomp-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://evcomp-api:8080/api
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - evcomp_default

networks:
  evcomp_default:
    external: true
